dist: trusty
language: generic
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- shellcheck gitardiff
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
