#!/bin/sh

# Copyright © 2015-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -ne 2 ]
then
    printf 'Usage: %s <tar1> <tar2>\n' "$0" >&2
    exit 1
fi

tar1="$1"
tar2="$2"
shift 2
tmpdir=$(mktemp -t -d gitardiff.XXXXXX)
gitdir="$tmpdir/git"
unpackdir="$tmpdir/unpack"
git init --quiet "$gitdir"
for tarfile in "$tar1" "$tar2"
do
    rm -rf "$unpackdir"
    mkdir "$unpackdir"
    date=$(LC_ALL=C stat -c '%y' "$tarfile")
    tar -C "$unpackdir" -xaf "$tarfile"
    git -C "$gitdir" config --replace-all core.worktree "$unpackdir"
    git -C "$gitdir" add -f -A .
    git -C "$gitdir" commit --quiet -m '' --allow-empty-message --date "$date"
done
rm -rf "$unpackdir"
git -c diff.renameLimit=999999 -C "$gitdir" show -M "$@"
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
