#!/bin/sh

# Copyright © 2015-2016 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u

if [ $# -ne 2 ]
then
    printf 'Usage: %s <tar1> <tar2>\n' "$0" >&2
    exit 1
fi

tar1="$1"
tar2="$2"
shift 2
tmpdir=$(mktemp -t -d gitardiff.XXXXXX)
gitdir="$tmpdir/git"
unpackdir="$tmpdir/unpack"
git init --quiet "$gitdir"
for tarfile in "$tar1" "$tar2"
do
    rm -rf "$unpackdir"
    mkdir "$unpackdir"
    date=$(LC_ALL=C stat -c '%y' "$tarfile")
    tar -C "$unpackdir" -xaf "$tarfile"
    git -C "$gitdir" config --replace-all core.worktree "$unpackdir"
    git -C "$gitdir" add -f -A .
    git -C "$gitdir" commit --quiet -m '' --allow-empty-message --date "$date"
done
rm -rf "$unpackdir"
git -c diff.renameLimit=999999 -C "$gitdir" show -M "$@"
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
