#!/bin/sh

# Copyright © 2015-2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -ne 2 ]
then
    me=${0##*/}
    printf 'Usage: %s TAR-FILE-1 TAR-FILE-2\n' "$me" >&2
    exit 1
fi

tar1="$1"
tar2="$2"
shift 2
tmpdir=$(mktemp -t -d gitardiff.XXXXXX)
n=0
for tarfile in "$tar1" "$tar2"
do
    n=$((n + 1))
    mkdir "$tmpdir/$n"
    tar -C "$tmpdir/$n" -xaf "$tarfile"
done
cd "$tmpdir"
mv 1 a
mv 2 b
git init --quiet .
git diff --no-index -l 65535 --src-prefix='' --dst-prefix='' a/ b/
cd /
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
